spring:
  application:
    name: competition-web

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competition_web
    username: root
    password: "111111"  # 如果密码是纯数字，建议用引号包裹

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

springdoc:
  api-docs:
    enabled: true  # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"

  swagger-ui:
    enabled: true  # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html  # 自定义路径，默认为"/swagger-ui/index.html"

ai:
  config:
    deepseek:
      apiKey: sk-8f5f75be58e84ab386644021728c36f2
      baseUrl: https://api.deepseek.com/chat/completions


